### PR TITLE
folder structure changed

### PR DESCRIPTION
**Pull request by mohammedfarisofficial**

### CODE REVIEW

**Comment by mohammedfarisofficial** [comment]
folder structure changed #42

**Comment by mohammedfarisofficial** [comment]
folder structure changed #42

**Comment by nandgator** [comment]
@mohammedfarisofficial should I close #41?

**Comment by mohammedfarisofficial** [comment]
Sure

**Comment by nandgator** [comment]
Why make a PR to push from `main` to `develop`?

**Comment by nandgator** [comment]
Okay never mind.

**Comment by nandgator** [comment]
Wait a min. I messed up the PR :man_facepalming:!

**Comment by nandgator** [comment]
image

What a mess!

**Pull request merged**
